version: '3'

services:
    nginx:
       build: .
       container_name: 'nginx-prueba'
       volumes:
         - ./nginx/conf.d/:/etc/nginx/conf.d/
         - ./html:/var/www
       ports:
          - "80:80"
       environment:
           - NGINX_PORT=80