version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: DockerfileNginx
    container_name: 'nginx-prueba'
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images:/var/images
      - ./html:/var/www
    ports:
      - '9000:80'
      - '400:400'
    environment:
      - NGINX_PORT=80

  express_app:
    build:
      context: .
      dockerfile: DockerfileExpress
    #container_name: express_app (cant have a name, bc its going to be duplicated)
    volumes:
      - ./app/express3:/app
      - ./rabbitMQ/:/app/rabbitMQ
    ports:
      - '3000'
    restart: always

  mongo:
    build:
      context: .
      dockerfile: DockerfileMongo
    restart: always
    volumes:
      - ./database/:/database/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    ports:
    # The standard AMQP protocol port
      - '5672:5672'
    # HTTP management UI
      - '15672:15672'
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 20s
      timeout: 10s
      retries: 5

  sendemail:
    links:
      - rabbitmq
    build:
      context: .
      dockerfile: ./DockerfileEmail